Create IntroductionWrapper molecule
bluemog/bluemog-web pull request #2
Opened 2021-04-10 08:08 UTC by 9ummy

IntroductionWrapper 분자와 스토리 생성

- 기본 형태

<img width="1206" alt="Screen Shot 2021-04-10 at 4 50 01 PM" src="https://user-images.githubusercontent.com/49152108/114263099-8a01c400-9a1e-11eb-8292-56aca0104543.png">

- 말줄임표 구현
<img width="1202" alt="Screen Shot 2021-04-10 at 4 49 52 PM" src="https://user-images.githubusercontent.com/49152108/114263101-8c641e00-9a1e-11eb-973e-eb2ce8329339.png">

<img width="1050" alt="Screen Shot 2021-04-10 at 4 49 28 PM" src="https://user-images.githubusercontent.com/49152108/114263103-8cfcb480-9a1e-11eb-9388-8e134f760e03.png">

div 태그 width, height 변경되면 line clamp도 변경할 수 있도록 props에 넣어두었습니다

2021-04-10 11:52 UTC, JSKeum commented
멋저요!

2021-04-10 12:00 UTC, JSKeum requested changes

2021-04-10 12:22 UTC, 9ummy commented on bluemog-client/src/components/molecules/IntroductionWrapper/index.tsx
> +      </p>
오 그렇군요

2021-04-10 12:27 UTC, 9ummy commented on bluemog-client/src/components/molecules/IntroductionWrapper/index.tsx
> +  font = 'Noto Sans KR',
맞아 안 그래도 이거 궁금했는데 그럼 상수 선언을 어디서 해줘야 하나요?!

2021-04-10 12:29 UTC, JSKeum commented on bluemog-client/src/components/molecules/IntroductionWrapper/index.tsx
> +    display: -webkit-box;
flex가 아닌 -webkit-box를 쓴 이유가 있나요??

2021-04-10 12:30 UTC, JSKeum commented on bluemog-client/src/components/molecules/IntroductionWrapper/index.tsx
> +  font = 'Noto Sans KR',
여러 컴포넌트 파일에서 쓰이니까 `src/constants/xx.ts` 이렇게 만들어서 쓰면 좋을 것 같아요!

2021-04-10 12:34 UTC, JSKeum commented on bluemog-client/src/components/molecules/IntroductionWrapper/index.tsx
> +    -webkit-box-orient: vertical;
앗 box-orient는 사용하지 않는게 좋다고 하네요!
https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient

2021-04-11 09:41 UTC, JSKeum approved these changes

2021-04-11 16:25 UTC, merged